disabled_rules:
  - line_length
  - todo
  - trailing_whitespace

opt_in_rules:
  - force_unwrapping
  - force_cast
  - empty_count
  - array_init

included:
  - SwiftLint/

excluded:
  - Pods/
  - Carthage/
  - build/

force_cast: warning
force_unwrapping: error

identifier_name:
  min_length: 2
  excluded:
    - id
    - URL
    - vm

type_body_length:
  warning: 200
  error: 300
