disabled_rules:
  - line_length
  - trailing_whitespace

opt_in_rules:
  - empty_count
  - closure_spacing
  - explicit_self

included:
  - SonarQube

excluded:
  - Pods
  - DerivedData

reporter: "xcode"

